const questions = [
  {
    id: 0,
    q: "What does the Program Counter do?",
    choices: [
      "continuously provides the ALU with the memory address of the <em class='bold'>next instruction</em> to be fetched from primary memory and carried out",
      "holds the current instruction being decoded and executed",
      "holds the contents found at the address held in the Memory Address Register (MAR)",
    ],
    answer: 0,
    questionRef: "CPU",
  },

  {
    id: 1,
    q: "What does the Memory Data Register do?",
    choices: [
      "holds instructions that haev been fetched from memory, or instructions that are about to be written to memory",
      "holds the address of the next instruction or piece of data that the CPU needs.",
      "continuously provides the ALU with the memory address of the next instruction to be fetched from primary memory and carried out",
    ],
    answer: 0,
    questionRef: "CPU",
  },
  {
    id: 2,
    q: "What does the accumulator do?",
    choices: [
      "temporarily holds the results of calculations done by the Arithmetic Logic Unit (ALU)",
      "holds the current instruction being decoded and executed",
      "holds the contents found at the address held in the Memory Address Register (MAR)",
    ],
    answer: 0,
    questionRef: "CPU",
  },
  {
    id: 3,
    q: "What does the Memory Address Register (MAR) do?",
    choices: [
      "Holds the address of the next instruction or piece of data that the CPU needs",
      "Holds the current instruction being decoded and executed",
      "Holds the contents found at the address held in the Memory Address Register (MAR) ",
    ],
    answer: 0,
    questionRef: "CPU",
  },

  {
    id: 4,
    q: "What does the Current Instruction Register do?",
    choices: [
      "Holds the current instruction being decoded and executed",
      "Continuously provides the ALU with the memory address of the next instruction to be fetched from primary memory and carried out",
      "Temporarily holds the results of calculations done by the Arithmetic Logic Unit (ALU)",
    ],
    answer: 0,
    questionRef: "CPU",
  },
  {
    id: 5,
    q: "What do all computers have?",
    choices: [
      "A CPU, memory, input devices and output devices",
      "A CPU, network interface card, input devices and output devices",
      "A CPU, firewall, input devices and output devices",
    ],
    answer: 0,
    questionRef: "CPU",
  },
  {
    id: 6,
    q: "Which list contains only input devices?",
    choices: [
      "graphics tablet, microphone, keyboard, mouse",
      "printer, scanner, monitor, optical pen",
      "monitor, printer, speakers, headphones",
    ],
    answer: 0,
    questionRef: "CPU",
  },
  {
    id: 7,
    q: "Which list contains only output devices?",
    choices: ["printer, speakers, monitor", "scanner, printer, headphones", "joystick, headphones, monitor"],
    answer: 0,
    questionRef: "CPU",
  },
  {
    id: 8,
    q: "Is a the following an input or output device?",
    q2: "keyboard",
    choices: ["input", "output"],
    answer: 0,
    questionRef: "CPU",
  },
  {
    id: 9,
    q: "Is a the following an input or output device?",
    q2: "mouse",
    choices: ["input", "output"],
    answer: 0,
    questionRef: "CPU",
  },
  {
    id: 10,
    q: "Is a the following an input or output device?",
    q2: "scanner",
    choices: ["input", "output"],
    answer: 0,
    questionRef: "CPU",
  },
  {
    id: 11,
    q: "Is a the following an input or output device?",
    q2: "optical pen",
    choices: ["input", "output"],
    answer: 0,
    questionRef: "CPU",
  },
  {
    id: 12,
    q: "Is a the following an input or output device?",
    q2: "joystick",
    choices: ["input", "output"],
    answer: 0,
    questionRef: "CPU",
  },
  {
    id: 13,
    q: "Is a the following an input or output device?",
    q2: "graphics tablet",
    choices: ["input", "output"],
    answer: 0,
    questionRef: "CPU",
  },
  {
    id: 14,
    q: "Is a the following an input or output device?",
    q2: "microphone",
    choices: ["input", "output"],
    answer: 0,
    questionRef: "CPU",
  },
  {
    id: 15,
    q: "Is a the following an input or output device?",
    q2: "headphones",
    choices: ["input", "output"],
    answer: 1,
    questionRef: "CPU",
  },
  {
    id: 16,
    q: "Is a the following an input or output device?",
    q2: "printer",
    choices: ["input", "output"],
    answer: 1,
    questionRef: "CPU",
  },
  {
    id: 17,
    q: "Is a the following an input or output device?",
    q2: "speakers",
    choices: ["input", "output"],
    answer: 1,
    questionRef: "CPU",
  },
  {
    id: 18,
    q: "Is a the following an input or output device?",
    q2: "monitor",
    choices: ["input", "output"],
    answer: 1,
    questionRef: "CPU",
  },
  {
    id: 19,
    q: "What is the best description of the purpose of the CPU?",
    choices: ["Repeatedly running the fetch-execute-decode cycle to carry out instructions from the computer's memory", "To store data in memory", "To carry out calculations"],
    answer: 0,
    questionRef: "CPU",
  },
  {
    id: 20,
    q: "Which option best describes what the CPU contains?",
    choices: ["The Arithmetic Logic Unit and the Control Unit, which each contain registers", "the Program Counter, Memory Address Register and Current Instruction Register", "the Memory Data Register and Accumulator"],
    answer: 0,
    questionRef: "CPU",
  },
  {
    id: 21,
    q: "What does the Arithmetic Logic Unit contain?",
    choices: ["the Memory Data Register and Accumulator", "the Program Counter, Memory Address Register and Current Instruction Register"],
    answer: 0,
    questionRef: "CPU",
  },
  {
    id: 21,
    q: "What does the Control Unit contain?",
    choices: ["the Program Counter, Memory Address Register and Current Instruction Register", "the Memory Data Register and Accumulator"],
    answer: 0,
    questionRef: "CPU",
  },
  {
    id: 22,
    q: "How would we add 'sister' to the end of the following list?",
    q2: "family = ['Mum', 'Dad', 'brother']",
    choices: ["family.append('sister')", "family.pop('sister')"],
    answer: 0,
    questionRef: "Python",
  },
  {
    id: 23,
    q: "How would we remove the item at index 0 from the list below?",
    q2: "favourite_foods = ['pizza', 'yoghurt', 'waffles', 'biryani']",
    choices: ["favourite_foods.pop(0)", "favourite_foods.pop(1)", "favourite_foods.pop()"],
    answer: 0,
    questionRef: "Python",
  },
  {
    id: 24,
    q: "How would we remove the last item from the list below?",
    q2: "favourite_foods = ['pizza', 'yoghurt', 'waffles', 'biryani']",
    choices: ["favourite_foods.pop()", "favourite_foods.pop(1)", "favourite_foods.pop(0)"],
    answer: 0,
    questionRef: "Python",
  },
  {
    id: 25,
    q: "How many values at a time can we add with append?",
    choices: ["one at a time", "we can add an unlimited number of values in one go"],
    answer: 0,
    questionRef: "Python",
  },
  {
    id: 26,
    q: "How many values at a time can we add with insert?",
    choices: ["one at a time", "we can add an unlimited number of values in one go"],
    answer: 0,
    questionRef: "Python",
  },
  {
    id: 27,
    q: "When we use 'append', where in the list does the appended value get added?",
    choices: ["at the end of the list", "at the beginning of the list"],
    answer: 0,
    questionRef: "Python",
  },


  // {
  //   id: 28,
  //   q: "exampleToCopy",
  //   choices: ["", ""],
  //   answer: 0,
  //   questionRef: "Python",
  // },
  // {
  //   id: 29,
  //   q: "exampleToCopy",
  //   choices: ["", ""],
  //   answer: 0,
  //   questionRef: "Python",
  // },
  // {
  //   id: 30,
  //   q: "exampleToCopy",
  //   choices: ["", ""],
  //   answer: 0,
  //   questionRef: "Python",
  // },
  

  // {
  //   id: 28,
  //   q: "exampleToCopy",
  //   choices: ["", ""],
  //   answer: 0,
  //   questionRef: "Python",
  // },




  // {
  //   id: 0,
  //   q: "exampleToCopy",
  //   choices: ["", "", ""],
  //   answer: [],
  //   questionRef: "CPU",
  // },
  // {
  //   id: 1,
  //   q: "exampleToCopy",
  //   choices: ["", "", ""],
  //   answer: [],
  //   questionRef: "CPU",
  // },
  // {
  //   id: 2,
  //   q: "exampleToCopy",
  //   choices: ["", "", ""],
  //   answer: [],
  //   questionRef: "CPU",
  // },
  // {
  //   id: 3,
  //   q: "exampleToCopy",
  //   choices: ["", "", ""],
  //   answer: [],
  //   questionRef: "CPU",
  // },
  // {
  //   id: 4,
  //   q: "exampleToCopy",
  //   choices: ["", "", ""],
  //   answer: [],
  //   questionRef: "CPU",
  // },
  // {
  //   id: 5,
  //   q: "exampleToCopy",
  //   choices: ["", "", ""],
  //   answer: [],
  //   questionRef: "CPU",
  // },
  // {
  //   id: 6,
  //   q: "exampleToCopy",
  //   choices: ["", "", ""],
  //   answer: [],
  //   questionRef: "CPU",
  // },
  // {
  //   id: 7,
  //   q: "exampleToCopy",
  //   choices: ["", "", ""],
  //   answer: [],
  //   questionRef: "CPU",
  // },
  // {
  //   id: 8,
  //   q: "exampleToCopy",
  //   choices: ["", "", ""],
  //   answer: [],
  //   questionRef: "CPU",
  // },
  // {
  //   id: 9,
  //   q: "exampleToCopy",
  //   choices: ["", "", ""],
  //   answer: [],
  //   questionRef: "CPU",
  // },
  // {
  //   id: 50,
  //   q: "exampleToCopy",
  //   choices: ["", "", ""],
  //   answer: [],
  //   questionRef: "CPU",
  // },
  // example of an image-based question
  // {
  //   id: 11,
  //   q: "How many squares are showing in this pic?",
  //   choices: ["3", "2", "1"],
  //   answer: 2,
  //   img: "img/square.jpg"
  // questionRef:
  //   }
];
